# Generated by Django 4.1 on 2024-05-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_zone_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='frequency',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='post_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='property_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.voucher'),
        ),
    ]
