# Generated by Django 4.1 on 2024-05-24 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_voucher_remove_booking_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='post_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.postcode'),
        ),
        migrations.CreateModel(
            name='SkillCostForZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cost_per_hour_normal_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_hour_public_holiday', models.DecimalField(decimal_places=2, max_digits=10)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workerskill')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.workerskill'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='worker_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.workerskill'),
        ),
        migrations.DeleteModel(
            name='WorkerSkills',
        ),
    ]
