# Generated by Django 4.1 on 2024-05-25 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workerskill_alter_booking_post_code_skillcostforzone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicHolidays',
            new_name='PublicHoliday',
        ),
        migrations.AddField(
            model_name='booking',
            name='managed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_booking_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
