# Generated by Django 4.1 on 2024-05-26 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_publicholidays_publicholiday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('property_type', models.CharField(max_length=50, null=True)),
                ('frequency', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('no_of_hours', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('worker_count', models.IntegerField()),
                ('transportation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('worker_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('booking_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.bookingstatus')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_booking_manager', to=settings.AUTH_USER_MODEL)),
                ('post_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.postcode')),
                ('voucher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.voucher')),
                ('worker_gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.gender')),
            ],
        ),
        migrations.AlterField(
            model_name='allocateworker',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cleanerbooking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cleanerbooking'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
