# Generated by Django 4.1 on 2024-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cleanerbooking_alter_allocateworker_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='discount',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
