# Generated by Django 4.1 on 2024-05-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_voucher_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerbooking',
            name='worker_gender',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
