# Generated by Django 4.1 on 2024-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_cleanerbooking_worker_gender_delete_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
