# Generated by Django 4.1 on 2024-06-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_addon_cleanerbooking_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleanerbooking',
            name='booking_created_date',
            field=models.DateField(null=True),
        ),
    ]
