# Generated by Django 4.1 on 2024-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_cleanerbooking_booking_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencyDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=50)),
                ('discount_perc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='addon',
            old_name='cost',
            new_name='cost_per_hour',
        ),
        migrations.AddField(
            model_name='cleanerbooking',
            name='addons',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cleanerbooking',
            name='addons_service_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
