# Generated by Django 4.1 on 2024-06-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cleanerbooking_addons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanerbooking',
            name='post_code',
            field=models.IntegerField(null=True),
        ),
    ]
